### PR TITLE
fix: ignore undefined piid and keep processing following arguments

### LINKED ISSUE #376: 米家吸顶灯D20持续产生雷达错误日志
### Describe the Bug / 描述问题

米家吸顶灯D20持续产生雷达错误日志

### How to Reproduce / 复现步骤

1. 米家绑定吸顶灯D20
2. HA正常登录米家账号
3. HA设置->系统->日志可见报错，约10s一次

### Expected Behavior / 预期结果

无报错

### Home Assistant Logs / 系统日志

详细日志可邮件联系

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System Version / Home Assistant Operation System 版本

N/A

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

### Additional Context / 其他说明

报错日志产生位置：https://github.com/XiaoMi/ha_xiaomi_home/blob/c1867e2baf4946f4666b7e4057509d2f615d3012/custom_components/xiaomi_home/miot/miot_device.py#L1218-L1221
`KeyError`异常来源：
https://github.com/XiaoMi/ha_xiaomi_home/blob/c1867e2baf4946f4666b7e4057509d2f615d3012/custom_components/xiaomi_home/miot/miot_device.py#L1205-L1207
其中`item['piid']`值为`14`，而`self._arguments_map`为`{24: '雷达事件类型'}`不包含`14`，产生`KeyError`异常
`self._arguments_map`在这里初始化：
https://github.com/XiaoMi/ha_xiaomi_home/blob/c1867e2baf4946f4666b7e4057509d2f615d3012/custom_components/xiaomi_home/miot/miot_device.py#L1164-L1166
所以错误日志产生的原因是event中包含了spec未定义的`piid`，且当前的逻辑会因为一个未定义的`piid`跳过后面其他的`piid`（即使是已定义的），导致`trans_arg`可能漏掉有用的`piid`。因此我认为只需要忽略这个`piid`即可，不需要生成错误日志。

### PR DESCRIPTION
**Pull request by RangerCD**
Fix #376 
- 忽略spec中未定义的piid并继续处理后续的arguments
- 错误日志改为debug日志

### CODE REVIEW

**Review by topsworld — APPROVED** [review]

**Comment by chemwolf6922** [comment]
@topsworld Should incomplete events be passed to the application? Will this cause problems?

**Comment by chemwolf6922** [comment]
@topsworld I think you should contact the PM or Hongyu to fix the broken spec to solve the original problem.

**Comment by RangerCD** [comment]
> @topsworld Should incomplete events be passed to the application? Will this cause problems?

If spec doesn't provide the definition of a piid, from intergration's perspective, it's something either redundant or unnecessary. Maybe it's a private argument used by Mijia App, and should be ignored by HA.

**Comment by topsworld** [comment]
> @topsworld I think you should also contact the PM or Hongyu to fix the broken spec to solve the original problem.

Done.

**Review by SusanPhevos — APPROVED** [review]

**Pull request merged**
