### PR TITLE
Fix local ctrl error

### PR DESCRIPTION
**Pull request by topsworld**
# Fixed
- Add profile devices filter, fix local control error

# Added
- Add tools to update profle model file

# Changed
- Improve lan control test case

It is necessary to realize the logic of profile convert specv2 later, so as to realize local control and subscribe to the Profile device

### CODE REVIEW

**Comment by chemwolf6922** [comment]
Suggestion: Just use the specV2 subscription result. Do not dive into the profile pitfall (again).

**Comment by chemwolf6922** [comment]
And the cloud has a field for telling if a device is "native spec V2" (for the central gateway). You should use that instead of any hard coded list.

**Comment by chemwolf6922** [comment]
And this (newly added) timeout seems suspiciously small. Please check if this is by design. 
https://github.com/XiaoMi/ha_xiaomi_home/blob/0af9e089ab40f26f3f165dcbf1f01e77baaf165e/custom_components/xiaomi_home/miot/miot_lan.py#L179

**Comment by chemwolf6922** [comment]
> Suggestion: Just use the specV2 subscription result. Do not dive into the profile pitfall (again).

Apparently there are device that supports the full subscription and also use the old protocol...

**Comment by topsworld** [comment]
> And this (newly added) timeout seems suspiciously small. Please check if this is by design.
> 
> https://github.com/XiaoMi/ha_xiaomi_home/blob/0af9e089ab40f26f3f165dcbf1f01e77baaf165e/custom_components/xiaomi_home/miot/miot_lan.py#L179

Is a bug  🫥

**Comment by topsworld** [comment]
> And the cloud has a field for telling if a device is "native spec V2" (for the central gateway). You should use that instead of any hard coded list.

The cloud interface provided does not have this field. This list contains the Profile device, and there will be no update in the future, so use HardCode

**Pull request merged**
